apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biocontainers.tacc.cloud
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-route53-tacc.cloud"
spec:
  tls:
    - hosts:
        - biocontainers.tacc.cloud
      secretName: biocontainers.tacc.cloud-tls
  rules:
    - host: biocontainers.tacc.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 5000
